/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MpiTest */

#ifndef _Included_MpiTest
#define _Included_MpiTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MpiTest
 * Method:    mpitest
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MpiTest_mpitest
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
