// This file was generated by the Ionate Transpiler
// Copyright Ionate(c) 2016 - 2025
package com.example.javaexamples.sort;

import java.util.List;
import java.util.function.Consumer;

/**
 * Sort file organization
 */
public interface SortFileOrganization {
  public void sort(SortOrder order, List<String> sortFields);
  public void release(Object obj);
  public void returnSort(Consumer<String> obj, Runnable atEnd, Runnable notAtEnd);
}
