/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class C */

#ifndef _Included_C
#define _Included_C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     C
 * Method:    atol
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_C_atol
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
