/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallConstr */

#ifndef _Included_CallConstr
#define _Included_CallConstr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallConstr
 * Method:    myNewString
 * Signature: ([CI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallConstr_myNewString
  (JNIEnv *, jobject, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
