/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassObjArray */

#ifndef _Included_PassObjArray
#define _Included_PassObjArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassObjArray
 * Method:    passArray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PassObjArray_passArray
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
